In [1]:
import numpy as np
import pandas as pd

## Numpy

In [ ]:
a = [1,2,3]
a

[1, 2, 3]

In [ ]:
a = np.array(a)
a

array([1, 2, 3])

In [ ]:
b = np.array(
    [[1,2,3,4],
    [5,6,7,8]]
)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#get dimension
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
#Shape
a.shape

(3,)

In [ ]:
b.shape

(2, 4)

In [ ]:
#type
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
b.itemsize

8

### acces and modifying

In [ ]:
c = [[1, 2, 3, 4],
       [5, 6, 7, 8]]
c[1][::2]

[5, 7]

In [ ]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
b[1,1]

6

In [ ]:
b[1, ::2]

array([5, 7])

In [ ]:
d = np.array(
    [
        [
            [1,2,3,4],
            [5,6,7,8]
        ],

        [
            [2,2,2,2],
            [1,3,4,5]
        ]
    ]
)

In [ ]:
d[1, 1, 3]

5

In [ ]:
d.ndim

3

In [ ]:
d.shape

(2, 2, 4)

### Initialize different array

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3), dtype = 'int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [ ]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.full_like(b, 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [ ]:
np.full(b.shape, 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [ ]:
np.random.rand(4,2)

array([[0.85029023, 0.79931532],
       [0.24266958, 0.34879919],
       [0.20887706, 0.98652441],
       [0.21626998, 0.0440395 ]])

In [ ]:
np.random.randint(-4, 8, size = (3,3))

array([[-4,  6,  6],
       [ 6,  0,  0],
       [-4,  6,  1]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
c = a.copy()
c[0] = 100
c

array([100,   2,   3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
a + 2

array([3, 4, 5])

In [ ]:
a*2

array([2, 4, 6])

In [ ]:
a/2

array([0.5, 1. , 1.5])

In [ ]:
b

array([4, 5, 6])

In [ ]:
a + b

array([5, 7, 9])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

### Linear Algebra

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [ ]:
v1 + v2

array([5, 7, 9])

In [ ]:
v1 - v2

array([-3, -3, -3])

In [ ]:
np.dot(v1, v2)

32

In [ ]:
v1 @ v2

32

In [ ]:
np.cross(v1, v2)

array([-3,  6, -3])

In [ ]:
np.linalg.norm(v1)

3.7416573867739413

In [ ]:
np.linalg.norm(v1, ord = 1)

6.0

In [ ]:
np.linalg.norm(v1, ord = np.inf)

3.0

In [ ]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
b = np.full((2,3), 2)
b

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.multiply(a,b)

array([[2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a = np.array([1,2,3])
np.reshape(a, (3,1))

array([[1],
       [2],
       [3]])

In [ ]:
inverse_matrix = np.array([[1,2], [3,4]])
np.linalg.inv(inverse_matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linalg.det(c)

1.0

In [ ]:
np.trace(c)

3.0

In [ ]:
eigen_matrix = np.array([[1,2], [1,2]])
val, vec = np.linalg.eig(eigen_matrix)

print(val)
print(vec)

[0. 3.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [ ]:
'''
3x + y = 9
x + 2y = 8
'''
A = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(A,b)
x

array([2., 3.])

### Statistics

In [ ]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats, axis = 1)

array([3, 6])

In [ ]:
np.sum(stats, axis = 1)

array([ 6, 15])

### Reorgainizing Array

In [ ]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

try:
  after = before.reshape((2,3))
  print(after)
except Exception as e:
  print(e)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
cannot reshape array of size 8 into shape (2,3)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
before.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
after.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
after = before.reshape((4,-1))
print(after)

print()
after = before.reshape((-1,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
 b

## Pandas

In [2]:
s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
print(s.index)
print(s.values)

RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [ ]:
x = np.array([1,2,3,4,5])
print(x)
print(s.values)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
print(type(s.values), type(x))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [3]:
fruits = ['Apple', "mangoes", 'oranges', 'watermelon']
q1 = [20, 10, 45, 32]
q2 = [17, 13, 31, 32]

x = pd.Series(q1, index = fruits)
x1 = pd.Series(q2, index = fruits)
print(x + x1)

Apple         37
mangoes       23
oranges       76
watermelon    64
dtype: int64


In [6]:
fruits2 = ['peaches', 'Apple', 'oranges', 'lemon']
s1 = pd.Series(q1, index = fruits)
s2 = pd.Series(q2, index = fruits2)
print(s1+s2)

Apple         33.0
lemon          NaN
mangoes        NaN
oranges       76.0
peaches        NaN
watermelon     NaN
dtype: float64


In [9]:
s1

Apple         20
mangoes       10
oranges       45
watermelon    32
dtype: int64

In [10]:
print(s1['Apple'])
print(s1[['mangoes', "Apple", 'oranges']])

20
mangoes    10
Apple      20
oranges    45
dtype: int64


In [11]:
print((s1+3)*2)

Apple         46
mangoes       26
oranges       96
watermelon    70
dtype: int64


In [12]:
s1.apply(np.log)

Apple         2.995732
mangoes       2.302585
oranges       3.806662
watermelon    3.465736
dtype: float64

In [13]:
s1

Apple         20
mangoes       10
oranges       45
watermelon    32
dtype: int64

In [15]:
s1.apply(lambda x: x*2 if x <= 25 else x + 10)

Apple         40
mangoes       20
oranges       55
watermelon    42
dtype: int64

In [16]:
s1[s1<20]

mangoes    10
dtype: int64

### Creating series from dictionary

In [17]:
cities = {
    "london" : 1234,
    "Berlin" : 4567,
    "Madrid" : 5678,
    "Rome" : 2545,
    "Paris" : 6597,
    "Vienna" : 4398,
    "Munich" : 9857,
    "Milan" : 3242
}

y = pd.Series(cities)
print(y)

london    1234
Berlin    4567
Madrid    5678
Rome      2545
Paris     6597
Vienna    4398
Munich    9857
Milan     3242
dtype: int64


In [19]:
my_cities = {"london", "Paris", "delhi", "Zurich", "Berlin"}
my_cities_series = pd.Series(cities, index = my_cities)
my_cities_series

Paris     6597.0
delhi        NaN
london    1234.0
Berlin    4567.0
Zurich       NaN
dtype: float64

In [21]:
my_cities_series.notnull()

Paris      True
delhi     False
london     True
Berlin     True
Zurich    False
dtype: bool

In [23]:
d = {'a' : 4, 'b': None, 'c': 5, 'd': 20}
s = pd.Series(d)
print(s)
pd.isnull(s)

a     4.0
b     NaN
c     5.0
d    20.0
dtype: float64


a    False
b     True
c    False
d    False
dtype: bool

In [24]:
print(my_cities_series.fillna(0))

Paris     6597.0
delhi        0.0
london    1234.0
Berlin    4567.0
Zurich       0.0
dtype: float64


In [25]:
missing = {"delhi": 2343, 'Zurich': 5324}
my_cities_series.fillna(missing)

Paris     6597.0
delhi     2343.0
london    1234.0
Berlin    4567.0
Zurich    5324.0
dtype: float64

### Dataframes

In [29]:
years = range(2014, 2018)
s1 = pd.Series([123, 456, 789, 432], index = years)
s2 = pd.Series([234, 465, 746, 768], index = years)
s3 = pd.Series([353, 487, 123, 658], index = years)
df = pd.concat([s1, s2, s3], axis = 1)
df

0    1    2
2014  123  234  353
2015  456  465  487
2016  789  746  123
2017  432  768  658

In [30]:
cities = ['a', 'b', 'c']
df.columns = cities
df

a    b    c
2014  123  234  353
2015  456  465  487
2016  789  746  123
2017  432  768  658

In [31]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [32]:
cities = {"City":  ["London", "Berlin", "Madrid", "Rome",
                    "Paris", "Vienna", "Bucharest", "Hamburg",
                    "Budapest", "Warsaw", "Barcelona",
                    "Munich", "Milan"],
          "population": [8615246, 3562166, 3165235, 2874038,
                         2273305, 1805681, 1803425, 1760433,
                         1754000, 1740119, 1602386, 1493900,
                         1350680],
          "country": ["England", "Germany", "Spain", "Italy",
                      "France", "Austria", "Romania",
                      "Germany", "Hungary", "Poland", "Spain",
                      "Germany", "Italy"] }

df = pd.DataFrame(cities)
df

City  population  country
0      London     8615246  England
1      Berlin     3562166  Germany
2      Madrid     3165235    Spain
3        Rome     2874038    Italy
4       Paris     2273305   France
5      Vienna     1805681  Austria
6   Bucharest     1803425  Romania
7     Hamburg     1760433  Germany
8    Budapest     1754000  Hungary
9      Warsaw     1740119   Poland
10  Barcelona     1602386    Spain
11     Munich     1493900  Germany
12      Milan     1350680    Italy

In [33]:
df.T

0        1        2        3        4        5          6   \
City         London   Berlin   Madrid     Rome    Paris   Vienna  Bucharest   
population  8615246  3562166  3165235  2874038  2273305  1805681    1803425   
country     England  Germany    Spain    Italy   France  Austria    Romania   

                 7         8        9          10       11       12  
City        Hamburg  Budapest   Warsaw  Barcelona   Munich    Milan  
population  1760433   1754000  1740119    1602386  1493900  1350680  
country     Germany   Hungary   Poland      Spain  Germany    Italy

In [34]:
pd.DataFrame.from_dict(cities, orient = 'index')

0        1        2        3        4        5          6   \
City         London   Berlin   Madrid     Rome    Paris   Vienna  Bucharest   
population  8615246  3562166  3165235  2874038  2273305  1805681    1803425   
country     England  Germany    Spain    Italy   France  Austria    Romania   

                 7         8        9          10       11       12  
City        Hamburg  Budapest   Warsaw  Barcelona   Munich    Milan  
population  1760433   1754000  1740119    1602386  1493900  1350680  
country     Germany   Hungary   Poland      Spain  Germany    Italy

In [36]:
df.reindex(columns = ['country', 'City', 'population'])

country       City  population
0   England     London     8615246
1   Germany     Berlin     3562166
2     Spain     Madrid     3165235
3     Italy       Rome     2874038
4    France      Paris     2273305
5   Austria     Vienna     1805681
6   Romania  Bucharest     1803425
7   Germany    Hamburg     1760433
8   Hungary   Budapest     1754000
9    Poland     Warsaw     1740119
10    Spain  Barcelona     1602386
11  Germany     Munich     1493900
12    Italy      Milan     1350680

In [38]:
df = df.set_index("country")
df

City  population
country                       
England     London     8615246
Germany     Berlin     3562166
Spain       Madrid     3165235
Italy         Rome     2874038
France       Paris     2273305
Austria     Vienna     1805681
Romania  Bucharest     1803425
Germany    Hamburg     1760433
Hungary   Budapest     1754000
Poland      Warsaw     1740119
Spain    Barcelona     1602386
Germany     Munich     1493900
Italy        Milan     1350680

In [42]:
df.loc["Germany"]

City  population
country                     
Germany   Berlin     3562166
Germany  Hamburg     1760433
Germany   Munich     1493900

In [43]:
df.loc[["Germany", "France"]]

City  population
country                     
Germany   Berlin     3562166
Germany  Hamburg     1760433
Germany   Munich     1493900
France     Paris     2273305

In [46]:
print(type(df.population))

<class 'pandas.core.series.Series'>


In [47]:
condition = df.population > 2000000
condition

country
England     True
Germany     True
Spain       True
Italy       True
France      True
Austria    False
Romania    False
Germany    False
Hungary    False
Poland     False
Spain      False
Germany    False
Italy      False
Name: population, dtype: bool

In [48]:
df.loc[condition]

City  population
country                    
England  London     8615246
Germany  Berlin     3562166
Spain    Madrid     3165235
Italy      Rome     2874038
France    Paris     2273305

In [49]:
condition2 = df['City'].str.contains('r')
df.loc[condition & condition2]

City  population
country                    
Germany  Berlin     3562166
Spain    Madrid     3165235
France    Paris     2273305

In [50]:
df

City  population
country                       
England     London     8615246
Germany     Berlin     3562166
Spain       Madrid     3165235
Italy         Rome     2874038
France       Paris     2273305
Austria     Vienna     1805681
Romania  Bucharest     1803425
Germany    Hamburg     1760433
Hungary   Budapest     1754000
Poland      Warsaw     1740119
Spain    Barcelona     1602386
Germany     Munich     1493900
Italy        Milan     1350680

In [51]:
milan = ["Milan", 12343252]
df.iloc[-1] = milan
df

City  population
country                       
England     London     8615246
Germany     Berlin     3562166
Spain       Madrid     3165235
Italy         Rome     2874038
France       Paris     2273305
Austria     Vienna     1805681
Romania  Bucharest     1803425
Germany    Hamburg     1760433
Hungary   Budapest     1754000
Poland      Warsaw     1740119
Spain    Barcelona     1602386
Germany     Munich     1493900
Italy        Milan    12343252

In [52]:
df.head(5)

City  population
country                    
England  London     8615246
Germany  Berlin     3562166
Spain    Madrid     3165235
Italy      Rome     2874038
France    Paris     2273305

In [53]:
from numpy.random import randint

df = pd.DataFrame(columns = ['name', 'x', 'y'])
for i in range(10):
  df.loc[i] = ['name' + str(i)] + list(randint(10, size = 2))

df

name  x  y
0  name0  5  9
1  name1  5  3
2  name2  2  3
3  name3  4  2
4  name4  5  2
5  name5  8  0
6  name6  5  4
7  name7  3  4
8  name8  2  3
9  name9  9  2

In [54]:
df.replace(to_replace = {"name": {"name0": "sumit", "name1": "kritika"}})

name  x  y
0    sumit  5  9
1  kritika  5  3
2    name2  2  3
3    name3  4  2
4    name4  5  2
5    name5  8  0
6    name6  5  4
7    name7  3  4
8    name8  2  3
9    name9  9  2

In [56]:
value = np.random.randint(1, 20, (30, ))
fruits = ["apple", 'mangoes', 'oranges', 'watermelon']
fruit_index = np.random.choice(fruits, (30, ))
s = pd.Series(value, fruit_index)
s[:10]

apple         15
oranges       11
watermelon     4
oranges       17
apple         10
watermelon    12
mangoes        1
mangoes       12
watermelon    15
apple          1
dtype: int64

In [58]:
grouped = s.groupby(s.index)
for fruit, obj in grouped:
  print(f"======{fruit}========")
  print(obj)

======apple========
apple    15
apple    10
apple     1
apple    11
apple    13
apple    13
apple     9
dtype: int64
======mangoes========
mangoes     1
mangoes    12
mangoes     5
mangoes     4
mangoes    13
mangoes    11
mangoes    16
dtype: int64
======oranges========
oranges    11
oranges    17
oranges     9
oranges     5
oranges    15
oranges     2
oranges    19
oranges    16
oranges    19
dtype: int64
======watermelon========
watermelon     4
watermelon    12
watermelon    15
watermelon    12
watermelon    11
watermelon    11
watermelon     7
dtype: int64
